# -*- coding: utf-8 -*-
"""Anggita-Nadia.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t4iWRx6S0iBz0DJU0AY_NA_NpzCPiONR
"""

a=int(input("Enter the 1st number: "))
b=int(input("Enter the 2nd number: "))
c=int(input("Enter the 3rd number: "))
d=int(input("Enter the 4th number: "))
if a > b and a > c and a > d:
  print(a, "is the bigger number.")
elif b > a and b > c and b > d:
  print(b, "is the bigger number.")
elif c > a and c > b and c > d:
  print(c, "is the bigger number.")
else:
  print(d, "is the bigger number.")

