# -*- coding: utf-8 -*-
"""Materi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15AvuATQSOqPftHr2GucqrPbwgcHK5mAM
"""

# Variable

a = 2 #integer / bilangan bulat
hewan = "Kuda" # String
#untuk yang dasarnya tidak ada yang namanya Char
b = 'A'  # String
c = True # Boolean
d = False # Boolean
e = 2.0 # Float
f = [] # List / Array
g = {} # Dictionary
h = () # Tuple

# Print

print(hewan)
print(2)
print(2+3)
print(True)

# Print 2
print("Nama hewannya adalah: " + hewan)
print("Nama hewannya adalah: {}".format(hewan))
print("Nama : {}, Tempat Tinggal : {}, Umur : {}".format("Gia", "Tangsel", 19))

Nama_Siswa = ["Keyra", "Ibay", "Nebula", "Ojan", "Bayu"]

print(Nama_Siswa[0])
print(Nama_Siswa[1])
print(Nama_Siswa[2])

Nama_Siswa

List_1 = ["Keyra"] * 5
List_1

Nama_Siswa[0:2]

Nama_Siswa[-2]

Nama_Siswa[-3:]

Nama_Siswa.append(1)
Nama_Siswa

Nama = "Keyra"
Tempat = "Tangsel"
Umur = 19
print("Nama : {}, Tempat Tinggal : {}, Umur : {}".format(Nama, Tempat, Umur))