# -*- coding: utf-8 -*-
"""nilai.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nd-b8UkojvrebJyZ2PDw2qLDAqFG1ejd
"""

print ("Nama : {}, Tempat tinggal : {}, Umur : {}, Movie : {}". format("Gia", "Tangsel", "19", "Frozen"))





